// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtPMDvmKWB-I5PzgMHJIDwpGRWfGL6GX8',
    appId: '1:397918798086:web:0efd14be04cf9f50cb5e87',
    messagingSenderId: '397918798086',
    projectId: 'speedlab-notif',
    authDomain: 'speedlab-notif.firebaseapp.com',
    storageBucket: 'speedlab-notif.firebasestorage.app',
    measurementId: 'G-RGH5TS33S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXTtYsJqDgnNk-arORZ7inAc9Ym4w4w9U',
    appId: '1:397918798086:android:6fdd5f4e9b856ab5cb5e87',
    messagingSenderId: '397918798086',
    projectId: 'speedlab-notif',
    storageBucket: 'speedlab-notif.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChdn5OA2NEJlIA-_BC5aktQPzIwnAThUM',
    appId: '1:397918798086:ios:f918f76ef62eb432cb5e87',
    messagingSenderId: '397918798086',
    projectId: 'speedlab-notif',
    storageBucket: 'speedlab-notif.firebasestorage.app',
    iosBundleId: 'com.example.speedlabPelanggan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChdn5OA2NEJlIA-_BC5aktQPzIwnAThUM',
    appId: '1:397918798086:ios:f918f76ef62eb432cb5e87',
    messagingSenderId: '397918798086',
    projectId: 'speedlab-notif',
    storageBucket: 'speedlab-notif.firebasestorage.app',
    iosBundleId: 'com.example.speedlabPelanggan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtPMDvmKWB-I5PzgMHJIDwpGRWfGL6GX8',
    appId: '1:397918798086:web:18f312e7186c9470cb5e87',
    messagingSenderId: '397918798086',
    projectId: 'speedlab-notif',
    authDomain: 'speedlab-notif.firebaseapp.com',
    storageBucket: 'speedlab-notif.firebasestorage.app',
    measurementId: 'G-KHX7KET46C',
  );
}
